services:
  vscode:
    build:
      context: .
      dockerfile: docker/vscode/Dockerfile

    image: orbit-vscode:latest

    container_name: orbit-vscode

    ports:
      - "8080:8443"

    environment:
      - TZ=Asia/Kolkata
      - PASSWORD=orbit

    volumes:
      - ./workspace:/config/workspace
      - vscode-data:/config

    restart: unless-stopped

volumes:
  vscode-data: